name: CI

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  formatting-and-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          pip install black isort ruff

      - name: Run isort
        run: isort .

      - name: Run black
        run: black duc
        env:
          CI: ""

      - name: Run ruff
        run: ruff check duc 

  run-pytest:
    needs: formatting-and-linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pytest httpx pytest-cov fastapi

      - name: Run pytest with coverage
        working-directory: ./duc
        run: |
          pytest tests --cov-report term --cov-report xml:coverage.xml --cov=./

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: duc/coverage.xml

  run-bandit:
    needs: formatting-and-linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security analysis
        working-directory: ./duc
        run: |
          bandit -r . -f json -o bandit-report.json --exit-zero

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: duc/bandit-report.json

  sonarqube-scan:
    needs: [run-bandit, run-pytest]
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Download Bandit report
      uses: actions/download-artifact@v4
      with:
        name: bandit-report
        path: duc

    - name: Download Coverage report
      uses: actions/download-artifact@v4
      with:
        name: coverage
        path: duc

    - name: Display structure of downloaded files
      run: ls -R duc/

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
