name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          pip install black isort ruff

      - name: Run isort
        run: isort .

      - name: Run black
        run: black --check duc

      - name: Run ruff
        run: ruff check duc

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          sonarqubeUrl: ${{ secrets.SONARQUBE_URL }}
          sonarqubeToken: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: .
